### ISSUE TITLE
No tests found with ReSharper 8.2.3  and Fixie 1.0.0.15 (does this still work?)

### ISSUE THREAD

**Issue by sstorie** [JohnStov/ReSharperFixieRunner#11]
I just tried using this plugin to run my Fixie tests within a WebAPI solution, but it's not finding any tests. I see some issues related to updates made within Fixie, so should this runner still work as is?

**Comment by JohnStov** [comment]
I've been very lax with this - I haven't made any changes for a long time.

To be honest, you're probably better off using the Visual Studio runner for
now.

**Comment by sstorie** [comment]
Ok, good to know. Thanks for creating this in the first place!
